server:
  servlet:
    context-path: /${spring.application.name}

logging:
  level:
    root: DEBUG
    org:
      springframework:
        web: ERROR

# feign log level
feign:
  client:
    config:
      feignName:
        loggerLevel: full

post:
  ribbon:
    listOfServers: https://jsonplaceholder.typicode.com
    ConnectTimeout: 20000
    ReadTimeout: 20000
    IsSecure: true

spring:
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

hystrix.command.default.execution:
  timeout.enabled: true
  isolation.thread.timeoutInMilliseconds: 50000
